from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Tuple
import json
import re
import uuid

from sqlalchemy import delete, select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models.wiki import WikiLog, WikiPage

_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?", re.DOTALL)

DEFAULT_SCHEMA = """# Wiki Schema

## Page Types

| Type | Directory | Purpose |
|------|-----------|---------|
| report | wiki/reports/ | Final research reports |
| topic | wiki/topics/ | Concepts and research topics |
| paper | wiki/papers/ | Academic papers |
| source | wiki/sources/ | Source summaries |
| comparison | wiki/comparisons/ | Comparative analysis |
| claim | wiki/claims/ | Evidence-backed claims |
| query | wiki/queries/ | Open questions and follow-up queries |

## Conventions

- Use kebab-case filenames.
- Use YAML frontmatter.
- Use [[wikilink]] for internal references.
"""

DEFAULT_PURPOSE = """# Project Purpose

This wiki stores reusable knowledge generated by the Research Lineage Assistant.
"""

DEFAULT_INDEX = """# Wiki Index

## Reports

## Topics

## Papers

## Sources

## Comparisons

## Claims

## Queries
"""

DEFAULT_OVERVIEW = """# Wiki Overview

This knowledge base is initialized and ready for research reports.
"""


def workspace_root() -> Path:
    configured = Path(settings.WIKI_WORKSPACE_PATH)
    if configured.is_absolute():
        return configured
    return (Path.cwd() / configured).resolve()


def slugify(value: str, fallback: str = "page") -> str:
    slug = re.sub(r"[^a-zA-Z0-9\u4e00-\u9fff]+", "-", value.strip().lower())
    slug = slug.strip("-")
    return slug or fallback


def today() -> str:
    return datetime.utcnow().date().isoformat()


def ensure_workspace() -> Path:
    root = workspace_root()
    for rel in [
        "raw/sources",
        "wiki/reports",
        "wiki/topics",
        "wiki/papers",
        "wiki/sources",
        "wiki/comparisons",
        "wiki/claims",
        "wiki/queries",
        ".llm-wiki",
    ]:
        (root / rel).mkdir(parents=True, exist_ok=True)

    defaults = {
        "purpose.md": DEFAULT_PURPOSE,
        "schema.md": DEFAULT_SCHEMA,
        "wiki/index.md": DEFAULT_INDEX,
        "wiki/log.md": "# Wiki Log\n",
        "wiki/overview.md": DEFAULT_OVERVIEW,
    }
    for rel, content in defaults.items():
        path = root / rel
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    return root


def safe_path(relative_path: str) -> Path:
    root = ensure_workspace()
    normalized = relative_path.replace("\\", "/").lstrip("/")
    if ".." in Path(normalized).parts:
        raise ValueError("Wiki path cannot contain '..'")
    path = (root / normalized).resolve()
    if root not in path.parents and path != root:
        raise ValueError("Wiki path escapes workspace")
    return path


def read_text(relative_path: str) -> str:
    path = safe_path(relative_path)
    return path.read_text(encoding="utf-8") if path.exists() else ""


def write_text(relative_path: str, content: str) -> str:
    path = safe_path(relative_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return relative_path.replace("\\", "/")


def list_markdown_files() -> List[Path]:
    root = ensure_workspace()
    return sorted(path for path in root.rglob("*.md") if path.is_file())


def relative_to_workspace(path: Path) -> str:
    return path.resolve().relative_to(workspace_root()).as_posix()


def parse_frontmatter(content: str, fallback_title: str) -> Tuple[Dict[str, Any], str]:
    match = _FRONTMATTER_RE.match(content)
    if not match:
        return {}, content

    frontmatter: Dict[str, Any] = {}
    for raw_line in match.group(1).splitlines():
        if ":" not in raw_line:
            continue
        key, value = raw_line.split(":", 1)
        key = key.strip()
        value = value.strip().strip('"')
        if value.startswith("[") and value.endswith("]"):
            try:
                frontmatter[key] = json.loads(value.replace("'", '"'))
            except json.JSONDecodeError:
                frontmatter[key] = [
                    item.strip().strip('"').strip("'")
                    for item in value.strip("[]").split(",")
                    if item.strip()
                ]
        else:
            frontmatter[key] = value

    frontmatter.setdefault("title", extract_title(content, fallback_title))
    body = content[match.end() :]
    return frontmatter, body


def extract_title(content: str, fallback_title: str) -> str:
    frontmatter_match = re.search(r"^title:\s*[\"']?(.+?)[\"']?\s*$", content, re.MULTILINE)
    if frontmatter_match:
        return frontmatter_match.group(1).strip()
    heading_match = re.search(r"^#\s+(.+)$", content, re.MULTILINE)
    if heading_match:
        return heading_match.group(1).strip()
    return fallback_title.replace(".md", "").replace("-", " ")


def extract_summary(body: str) -> str:
    paragraphs = [line.strip() for line in body.splitlines() if line.strip() and not line.startswith("#")]
    return " ".join(paragraphs)[:600]


def as_list(value: Any) -> List[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item).strip()]
    if isinstance(value, str) and value:
        return [value]
    return []


async def upsert_page_from_file(db: AsyncSession, path: Path) -> WikiPage:
    rel_path = relative_to_workspace(path)
    content = path.read_text(encoding="utf-8")
    frontmatter, body = parse_frontmatter(content, path.name)
    title = str(frontmatter.get("title") or extract_title(content, path.name))
    page_type = str(frontmatter.get("type") or infer_page_type(rel_path))
    summary = str(frontmatter.get("summary") or extract_summary(body))
    tags = as_list(frontmatter.get("tags"))
    sources = as_list(frontmatter.get("sources"))
    related = [*as_list(frontmatter.get("related")), *extract_wikilinks(content)]
    related = sorted(set(item for item in related if item))

    result = await db.execute(select(WikiPage).where(WikiPage.path == rel_path))
    page = result.scalar_one_or_none()
    if page is None:
        page = WikiPage(
            id=str(uuid.uuid4()),
            title=title,
            path=rel_path,
            page_type=page_type,
            summary=summary,
            content=content,
            tags=tags,
            sources=sources,
            related=related,
            extra_metadata=frontmatter,
        )
        db.add(page)
    else:
        page.title = title
        page.page_type = page_type
        page.summary = summary
        page.content = content
        page.tags = tags
        page.sources = sources
        page.related = related
        page.extra_metadata = frontmatter
        page.updated_at = datetime.utcnow()

    await db.flush()
    await index_page_fts(db, page)
    return page


async def index_page_fts(db: AsyncSession, page: WikiPage) -> None:
    await db.execute(text("DELETE FROM wiki_page_fts WHERE page_id = :page_id"), {"page_id": page.id})
    await db.execute(
        text(
            """
            INSERT INTO wiki_page_fts(page_id, title, path, page_type, summary, content, tags)
            VALUES (:page_id, :title, :path, :page_type, :summary, :content, :tags)
            """
        ),
        {
            "page_id": page.id,
            "title": page.title,
            "path": page.path,
            "page_type": page.page_type,
            "summary": page.summary or "",
            "content": page.content,
            "tags": " ".join(page.tags or []),
        },
    )


async def reindex_workspace(db: AsyncSession) -> int:
    ensure_workspace()
    await db.execute(delete(WikiPage))
    await db.execute(text("DELETE FROM wiki_page_fts"))
    count = 0
    for path in list_markdown_files():
        await upsert_page_from_file(db, path)
        count += 1
    await append_log(db, "reindex", None, None, f"Reindexed {count} wiki page(s)")
    await db.commit()
    return count


async def append_log(
    db: AsyncSession,
    action_type: str,
    research_id: str | None,
    page_path: str | None,
    message: str,
) -> WikiLog:
    log = WikiLog(
        id=str(uuid.uuid4()),
        action_type=action_type,
        research_id=research_id,
        page_path=page_path,
        message=message,
    )
    db.add(log)
    return log


def infer_page_type(path: str) -> str:
    parts = path.split("/")
    if len(parts) >= 2 and parts[0] == "wiki":
        directory = parts[1]
        return {
            "reports": "report",
            "topics": "topic",
            "papers": "paper",
            "sources": "source",
            "comparisons": "comparison",
            "claims": "claim",
            "queries": "query",
        }.get(directory, "overview")
    return "system"


def extract_wikilinks(content: str) -> List[str]:
    return [match.group(1).strip() for match in re.finditer(r"\[\[([^\]|]+)(?:\|[^\]]+)?\]\]", content)]


def frontmatter_block(
    title: str,
    page_type: str,
    tags: List[str] | None = None,
    sources: List[str] | None = None,
    related: List[str] | None = None,
) -> str:
    date = today()
    return "\n".join(
        [
            "---",
            f'title: "{title}"',
            f"type: {page_type}",
            f"tags: {json.dumps(tags or [])}",
            f"sources: {json.dumps(sources or [])}",
            f"related: {json.dumps(related or [])}",
            f"created_at: {date}",
            f"updated_at: {date}",
            "---",
            "",
        ]
    )
