<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { wikiApi } from '@/services/api'
import type { WikiLintResult, WikiLog, WikiPage, WikiSearchResult } from '@/types'
import AppLoading from '@/components/common/AppLoading.vue'

const pages = ref<WikiPage[]>([])
const results = ref<WikiSearchResult[]>([])
const logs = ref<WikiLog[]>([])
const issues = ref<WikiLintResult[]>([])
const selected = ref<WikiPage | null>(null)
const query = ref('')
const loading = ref(false)
const actionMessage = ref<string | null>(null)
const error = ref<string | null>(null)

const visiblePages = computed(() => (results.value.length ? results.value : pages.value))
const pageCountByType = computed(() => {
  return pages.value.reduce<Record<string, number>>((acc, page) => {
    acc[page.page_type] = (acc[page.page_type] ?? 0) + 1
    return acc
  }, {})
})

async function loadWiki() {
  loading.value = true
  error.value = null
  try {
    const [pageResponse, logResponse] = await Promise.all([wikiApi.getPages(), wikiApi.getLogs()])
    pages.value = pageResponse.data
    logs.value = logResponse.data
    selected.value = selected.value ?? pages.value[0] ?? null
  } catch (e) {
    error.value = (e as Error).message
  } finally {
    loading.value = false
  }
}

async function runSearch() {
  error.value = null
  try {
    const { data } = await wikiApi.search(query.value)
    results.value = data
    if (data[0]) await openPage(data[0].id)
  } catch (e) {
    error.value = (e as Error).message
  }
}

async function openPage(id: string) {
  try {
    const { data } = await wikiApi.getPage(id)
    selected.value = data
  } catch (e) {
    error.value = (e as Error).message
  }
}

async function reindex() {
  loading.value = true
  actionMessage.value = null
  try {
    const { data } = await wikiApi.reindex()
    actionMessage.value = data.message
    results.value = []
    await loadWiki()
  } catch (e) {
    error.value = (e as Error).message
  } finally {
    loading.value = false
  }
}

async function lint() {
  actionMessage.value = null
  try {
    const { data } = await wikiApi.lint()
    issues.value = data
    actionMessage.value = `Found ${data.length} structural issue(s)`
  } catch (e) {
    error.value = (e as Error).message
  }
}

onMounted(loadWiki)
</script>

<template>
  <div class="wiki-view">
    <section class="wiki-view__hero">
      <div>
        <p class="wiki-view__eyebrow">LLM Wiki</p>
        <h1>Reusable research memory</h1>
        <p>Reports and source summaries generated by the research agent are stored here as Markdown knowledge.</p>
      </div>
      <div class="wiki-view__actions">
        <button @click="reindex">Reindex</button>
        <button @click="lint">Lint</button>
      </div>
    </section>

    <AppLoading v-if="loading && !pages.length" text="Loading wiki..." />
    <p v-if="error" class="wiki-view__error">{{ error }}</p>
    <p v-if="actionMessage" class="wiki-view__message">{{ actionMessage }}</p>

    <section class="wiki-view__stats">
      <span v-for="(count, type) in pageCountByType" :key="type">{{ type }}: {{ count }}</span>
    </section>

    <section class="wiki-view__shell">
      <aside class="wiki-view__list">
        <form class="wiki-view__search" @submit.prevent="runSearch">
          <input v-model="query" placeholder="Search wiki memory..." />
          <button>Search</button>
        </form>

        <button
          v-for="page in visiblePages"
          :key="page.id"
          class="wiki-view__item"
          :class="{ 'wiki-view__item--active': selected?.id === page.id }"
          @click="openPage(page.id)"
        >
          <strong>{{ page.title }}</strong>
          <span>{{ page.page_type }} / {{ page.path }}</span>
          <p>{{ page.summary }}</p>
        </button>
      </aside>

      <main class="wiki-view__page">
        <template v-if="selected">
          <div class="wiki-view__page-header">
            <div>
              <span>{{ selected.page_type }}</span>
              <h2>{{ selected.title }}</h2>
              <p>{{ selected.path }}</p>
            </div>
          </div>
          <pre>{{ selected.content }}</pre>
        </template>
        <p v-else class="wiki-view__empty">No Wiki page selected.</p>
      </main>
    </section>

    <section v-if="issues.length" class="wiki-view__panel">
      <h2>Lint Issues</h2>
      <div v-for="issue in issues" :key="`${issue.type}-${issue.page}-${issue.detail}`">
        <strong>{{ issue.severity }} / {{ issue.type }}</strong>
        <p>{{ issue.page }}: {{ issue.detail }}</p>
      </div>
    </section>

    <section class="wiki-view__panel">
      <h2>Recent Wiki Logs</h2>
      <div v-for="log in logs.slice(0, 8)" :key="log.id">
        <strong>{{ log.action_type }}</strong>
        <p>{{ log.message }}</p>
      </div>
    </section>
  </div>
</template>

<style scoped>
.wiki-view {
  width: min(1180px, 100%);
  min-height: 100vh;
  margin: 0 auto;
  padding: var(--space-8) var(--space-6);
}

.wiki-view__hero,
.wiki-view__shell,
.wiki-view__page-header,
.wiki-view__actions,
.wiki-view__stats {
  display: flex;
  gap: var(--space-4);
}

.wiki-view__hero {
  align-items: flex-start;
  justify-content: space-between;
  margin-bottom: var(--space-6);
}

.wiki-view__eyebrow {
  color: #8b867c;
  font-size: var(--text-xs);
  font-weight: 800;
  letter-spacing: 0.1em;
  margin: 0 0 var(--space-2);
  text-transform: uppercase;
}

.wiki-view h1 {
  color: #171717;
  font-size: clamp(2rem, 4vw, 3.4rem);
  letter-spacing: -0.045em;
  margin: 0;
}

.wiki-view__hero p,
.wiki-view__item p,
.wiki-view__page-header p,
.wiki-view__panel p,
.wiki-view__empty {
  color: #68645d;
  line-height: 1.6;
}

.wiki-view__actions button,
.wiki-view__search button {
  border: 0;
  border-radius: var(--radius-full);
  background: #171717;
  color: #fff;
  cursor: pointer;
  font: inherit;
  font-weight: 700;
  padding: var(--space-2) var(--space-4);
}

.wiki-view__stats {
  flex-wrap: wrap;
  margin-bottom: var(--space-4);
}

.wiki-view__stats span,
.wiki-view__page-header span {
  border-radius: var(--radius-full);
  background: #f2efe8;
  color: #4b4945;
  font-size: var(--text-xs);
  font-weight: 800;
  padding: var(--space-1) var(--space-3);
}

.wiki-view__shell {
  align-items: stretch;
  min-height: 640px;
}

.wiki-view__list,
.wiki-view__page,
.wiki-view__panel {
  border: 1px solid #e7e2d8;
  border-radius: 28px;
  background: #fff;
  box-shadow: 0 18px 70px rgb(23 23 23 / 0.06);
}

.wiki-view__list {
  display: grid;
  align-content: start;
  gap: var(--space-2);
  width: 360px;
  max-height: 720px;
  overflow-y: auto;
  padding: var(--space-4);
}

.wiki-view__search {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: var(--space-2);
  margin-bottom: var(--space-2);
}

.wiki-view__search input {
  border: 1px solid #dedbd3;
  border-radius: var(--radius-full);
  color: #171717;
  font: inherit;
  outline: none;
  padding: var(--space-2) var(--space-3);
}

.wiki-view__item {
  border: 0;
  border-radius: var(--radius-xl);
  background: transparent;
  cursor: pointer;
  display: grid;
  gap: var(--space-1);
  padding: var(--space-3);
  text-align: left;
}

.wiki-view__item--active,
.wiki-view__item:hover {
  background: #f2efe8;
}

.wiki-view__item strong {
  color: #242321;
}

.wiki-view__item span {
  color: #8b867c;
  font-size: var(--text-xs);
}

.wiki-view__page {
  flex: 1;
  min-width: 0;
  padding: var(--space-6);
}

.wiki-view__page-header {
  align-items: flex-start;
  justify-content: space-between;
  border-bottom: 1px solid #eeeae2;
  margin-bottom: var(--space-4);
  padding-bottom: var(--space-4);
}

.wiki-view__page h2,
.wiki-view__panel h2 {
  color: #171717;
  margin: var(--space-2) 0 0;
}

.wiki-view__page pre {
  color: #242321;
  font-family: var(--font-sans);
  line-height: 1.7;
  margin: 0;
  overflow-x: auto;
  white-space: pre-wrap;
}

.wiki-view__panel {
  display: grid;
  gap: var(--space-3);
  margin-top: var(--space-5);
  padding: var(--space-5);
}

.wiki-view__message {
  color: #116039;
}

.wiki-view__error {
  color: var(--color-error);
}

@media (max-width: 860px) {
  .wiki-view {
    padding: var(--space-6) var(--space-4);
  }

  .wiki-view__hero,
  .wiki-view__shell {
    flex-direction: column;
  }

  .wiki-view__list {
    width: auto;
  }
}
</style>
